name: app-django-vue
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    resources:
      cpu: 100m
      memory: 128Mi
  
  backend:
    public: true
    image: okteto.dev/app-docker-django-vue-postgree-django:okteto
    build: 
      context: ./backend
    volumes:
      - .:/code
    replicas: 1
    ports:
      - 8000:8000
    depends_on:
      - db
    resources:
      cpu: 100m
      memory: 128Mi
    
  frontend:
    public: true
    image: okteto.dev/app-docker-django-vue-postgree-vue:okteto
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/app/src
    replicas: 1
    ports:
      - 8080:8080
    depends_on:
      - backend
    resources:
      cpu: 500m
      memory: 64Mi